### ISSUE TITLE
Sometimes we see an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#2389] opened 2021-10-26 08:57 UTC
**Describe the issue**
After upgrading to FF! 7.7-20211013.103955, we sometimes see an ArrayIndexOutOfBoundsException.
With a retry from the errorstore the messages can be processed succesfully. This exception does not always occur.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/35798481/138829531-e9cac149-cd8f-4728-a2ba-682305277ee2.png)

**Configuration**

**Input**
see attached stacktraces

**Environment**
FF! 7.7-20211013.103955: Ibis4Titan 399-496fcf1d-release7-7
Running on srtzzapp0406.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.25 - pxa6480sr6fp25-20210115_01(SR6 FP25))
Heap size: 555M, total JVM memory: 1536M
Free disk space: 8GB, total disk space: 10GB
Up since: 2021-10-25 13:41:17 (19h)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
[stacktrace2.txt](https://github.com/ibissource/iaf/files/7416106/stacktrace2.txt)
[stacktrace1.txt](https://github.com/ibissource/iaf/files/7416107/stacktrace1.txt)

**Comment by jacodg** [comment] 2021-10-30 16:33
Based on the stacktrace (see relevant part below) I received by email I was able to reproduce the ArrayIndexOutOfBoundsException with a Ladybug JUnit test. I pushed https://github.com/ibissource/ibis-ladybug/commit/9a8b11ad83f09ac4dba8a87f94a4a2273e949f3e to the Ladybug project to fix it. And submitted https://github.com/ibissource/iaf/pull/2405 to bump the Ladybug version in F!F to the latest version that includes this fix. I still need to work on the JUnit test to assert all situations correctly (due to concurrency the unit test has several different outcomes depending on which thread will run faster) but I'll look into that when I have more time (didn't have much time last week and don't expect to have much time coming week). The fix should be okay though.

If I'm correct the ArrayIndexOutOfBoundsException would only occur in rare/unusual cases where one thread is closing the report and another one is opening it in parallel (using the same correlationId). I would not expect that to happen for an adapter/pipeline. Hence, could you, after installing this fix on T, keep an eye on the Ladybug reports for the adapter(s) that suffered ArrayIndexOutOfBoundsExceptions? And see whether now maybe 2 reports are generated with the same correlationId? Or maybe some other symptoms like some pipes or senders being reported in separate reports?

```
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.util.ArrayList.elementData(ArrayList.java:435) ~[?:1.8.0]
	at java.util.ArrayList.get(ArrayList.java:448) ~[?:1.8.0]
	at nl.nn.testtool.Report.checkpoint(Report.java:292) ~[ibis-ladybug-2.2-20210820.122759.jar:2.2-20210820.122759]
	at nl.nn.testtool.TestTool.checkpoint(TestTool.java:289) ~[ibis-ladybug-2.2-20210820.122759.jar:2.2-20210820.122759]
	at nl.nn.testtool.TestTool.startpoint(TestTool.java:377) ~[ibis-ladybug-2.2-20210820.122759.jar:2.2-20210820.122759]
	at nl.nn.ibistesttool.Debugger.pipeLineInput(Debugger.java:85) ~[ibis-adapterframework-ladybug-7.7-20211013.103955.jar:7.7-20211013.103955]
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:108) ~[ibis-adapterframework-ladybug-7.7-20211013.103955.jar:7.7-20211013.103955]

```

**Closed** 2021-11-01 08:12 UTC
