### ISSUE TITLE
ForEachChilldElementPipe fails on encoding

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#926] opened 2020-07-10 13:17 UTC
**Describe the bug**
I have a ForEachChildElementPipe that had processFile=true and the file has <?xml version="1.0" encoding="utf-16"?> as XML declaration, while it actually is UTF-8. When processing a message (input=complete path to the file), I get the error "Could not process list of elements using xpath [xyz/abc]: (SAXParseException) line [1] column [40]: Content is not allowed in prolog".

When first doing a read with a FilePipe and using that as input for the ForEachChildElementPipe (without processFile), the file is correctly processed. Doing the same with a LocalFileSystemPipe does not work and results in the same error as it passes the file as stream to the ForEachChildElementPipe.

**Reporter**
Ricardo

**Category**
 - Frank Framework

**To Reproduce**
Steps to reproduce the behavior: (TBD)
1. Load the attached configurations
2. Download the attached file "Repro.xml"
3. Click on 'Test a Pipeline'
4. Select the adapter ForEachRepro and give as input the complete path to the "Repro.xml" file
5. Send and see failure
6. Change adapter to ForEachReproReadFile and send again
7. See success

**Expected behavior**
ForEachChildElementPipe not failing on an encoding-issue.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): WebSphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.5-RC3, 7.6 SNAPSHOT

**Additional context**
[resources.zip](https://github.com/ibissource/iaf/files/4911572/resources.zip)

**Comment by ricardovh** [comment] 2020-07-13 09:39
Added reproduction and clearer description to issue.

**Comment by nielsm5** [comment] 2020-07-13 12:12
Is this a duplicate of issue #911 and has it been fixed in PR #916?

**Comment by ricardovh** [comment] 2020-07-13 12:25
> Is this a duplicate of issue #911 and has it been fixed in PR #916?

It does not seem to be a duplicate of #911, that seems to be an issue with creating an XML from some input, while this is about reading an XML from file with some encoding issue (or something in that direction).

I tested against 7.6-20200713.101805 which includes #916, also checked if adding the escapeXml would help, but the error is still there.

**Comment by gvanbrakel** [comment] 2020-07-17 08:13
The problem here is that the file Repro.xml declares that it is encoded in utf-16, but actually it is encoded in utf-8.
When using processFile=true, the file is read as binary, and the encoding is determined from the declaration to be utf-16, which it is not. Same holds when using the LocalFileSystemPipe: this reads the file in a binary way.
The FilePipe, however, does not interpret the XML declaration, and reads the file in platform encoding and forwards it as a String.

**Closed** 2020-07-21 06:35 UTC
