### ISSUE TITLE
When property "strutsConsole.enabled" is true, I still cannot open GUI 1.2

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#863] opened 2020-06-23 08:20 UTC
**Describe the bug**
When I try to select GUI 1.2 in the main menu of the FF!, I get the error message shown at the screenshots section. That text asks to set property "strutsConsole.enabled" to true. But when I do this, the same error shows up again when I want to open GUI 1.2.

**Reporter**
Martijn Dirkse

**Category**
 - Frank Console

**To Reproduce**
1. Start the Frank!Framework with some configuration. Ensure that property "strutsConsole.enabled" is set to true.
2. In the main menu, select "GUI 1.2"
3. You see the error.

**Expected behavior**
With the mentioned property set to true, you should see GUI 1.2 when you select it in the main menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/6784732/85378001-3b8c4300-b53a-11ea-977a-d6c79e200f02.png)

**Environment:**
 - Apache Tomcat
 - Microsoft Edge
 - FF! version 7.6-20200619.155110

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment] 2020-06-24 12:19
Hi Martijn,

I'm assuming you've restarted your server after setting the propery. Did you also reload your browser?

**Comment by mhdirkse** [comment] 2020-06-24 12:53
I successfully opened GUI 1.2. I did the following:

* I had Microsoft Edge open. There was no tab with the Frank!Framework.
* I started the Frank!Runner with the following command:

      start.bat -DstrutsConsole.enabled=true -Djdbc.migrator.active=true

* The Frank!Runner downloaded version 7.6-20200624.105213 of the Frank!Framework and installed it.
* In the main menu, I selected "GUI 1.2". That GUI appeared.

**Comment by nielsm5** [comment] 2020-07-01 13:00
I think this is a duplicate of #892, can you confirm this?

**Comment by mhdirkse** [comment] 2020-07-02 18:09
Yes, it is a duplicate.

**Comment by nielsm5** [comment] 2020-07-13 12:10
Okey, then I'll close this issue.

**Closed by nielsm5** 2020-07-13 12:10 UTC

**Comment by mhdirkse** [comment] 2020-07-15 10:14
I still have to refresh my browser before it works.

**Comment by mhdirkse** [comment] 2020-07-15 10:16
I remember again: When I restart the Frank!Runner, the GUI looses the connection with the server. It cannot be expected to work without a browser refresh. I have thus verified this issue.
