### ISSUE TITLE
Ladybug starts a new report for each call from IbisLocalSender to JavaListener

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#4957] opened 2023-06-07 10:31 UTC
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Since a few weeks, Ladybug starts a new report when an IbisLocalSender calls a JavaListener. The flow of the called adapter appears in the new report and is not present in the report of the calling adapter. Jaco suggested that something may be wrong with the correlationId. Initially I thought this was an issue of ibis-ladybug, see https://github.com/ibissource/ibis-ladybug/issues/193, but Jaco said to me that it is in the Frank!Framework.

Here is how this looks like in ZaakBrug:

![image](https://github.com/ibissource/iaf/assets/6784732/2e163c8b-12b8-401b-9455-aa57339801b2)

**Reporter**
Martijn Dirkse

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9-20230530.190019: ZaakBrug
Running on 420662a04158 using Apache Tomcat/8.5.85
Java Version: OpenJDK Runtime Environment (1.8.0_362-b09)
Heap size: 945M, total JVM memory: 1174M
Free disk space: 44GB, total disk space: 58GB
Up since: 2023-06-07 12:28:35 (2m)```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment] 2023-06-08 12:32
Seems to be a duplicate of #4224 ?

**Comment by mhdirkse** [comment] 2023-06-09 10:41
Issue #4224 is quite old; it is from December 2022. We did not see this problem in ZaakBrug before May I think. Maybe issue #4224 was solved without the issue report being updated. Then the issue may have been reintroduced more recently.

**Comment by nielsm5** [comment] 2023-06-09 10:58
Has synchronous been set to false or not?

**Comment by MLenterman** [comment] 2023-06-09 13:07
> Has synchronous been set to false or not?
synchronous has not been set to false.

**Comment by nielsm5** [comment] 2023-06-09 14:49
Then it's not a duplicate! 😭

**Comment by tnleeuw** [comment] 2023-06-22 11:09
I checked the 7.8 branch and it looks like the issue will not appear there.

**Closed** 2023-06-22 15:35 UTC
