### ISSUE TITLE
JSON to XML with xs:anyType does not work

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3088] opened 2022-04-20 10:21 UTC
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When using the Json2XmlValidator to convert JSON to XML, any xs:anyType in the underlying XSD is not converted.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment] 2022-04-21 06:42
might be duplicate of #2792

**Comment by ricardovh** [comment] 2022-04-21 08:48
If there is no information what can be expected, I think a "best effort guess" of converting everything to elements should then be done instead of just dropping the information. Then if it is not the right format for the usecase, it  at least has a format that can be directly and easily transformed using XSLT, instead of requiring some workarounds (like processing the JSON also with the JsonPipe and then merge the results).

**Closed** 2022-04-26 16:04 UTC
