### ISSUE TITLE
Setting lock is part of transaction

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#778] opened 2020-06-02 07:35 UTC
**Describe the bug**
When having a job with a locker and transactionAttribute set to Required or RequiresNew, the setting of the lock is part of the transaction. As the transaction is commited only at the end of the job, the lock is not really set (unlock is in the same transaction commit), allowing multiple nodes to execute the job at the same time while this is not intended.

**Reporter**
Ricardo

**Category**
 - Frank Framework

**To Reproduce**
1. Define a job with transactionAttribute=Required and a lock (calling an adapter with a DelayPipe)
2. Run this on two nodes
3. Wait for the job to execute
4. See that job is executed on both nodes

**Expected behavior**
Locking and unlocking the job should not be part of the transaction.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat/Websphere
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200421.151810

**Additional context**
N/A

**Comment by jjansenvr** [comment] 2020-06-17 10:43
Hi Ricardo

where do you have your transaction attribute? is it on the scheduler/ receiver or pipeline

I have a case with a scheduler and the transaction attribute "required" on the pipeline. Sometimes the process is started on both nodes most of the times no problems occur

you think this is the same issue?

**Comment by gvanbrakel** [comment] 2020-11-16 13:27
Lock does not appear to work, because the lock that is set by one thread is not seen by other threads,

**Comment by gvanbrakel** [comment] 2020-12-17 07:51
See also #1075. 
For proper operation, lock should be set in a separate transaction. 
The actual behaviour depends on the type of locking employed by the database. When optimistic locking is used, the effect of the lock being set is only seen by other transactions if the transaction has been committed.

**Comment by gvanbrakel** [comment] 2020-12-18 07:09
proposed approach:
- create test for Locker (extending JdbcTestBase)
- create test for Job with Locker (extending JdbcTestBase)
- refactor Locker, so that it returns boolean, and does not throw exceptions normally
- modify Job, so that setting locker is effective (in a separate transaction)
- improve or remove iaf-test config ConfigurationLocker.xml

**Comment by alisihab** [comment] 2021-01-06 14:36
changes have been committed to branch _lockerOwnTransaction_

**Comment by gvanbrakel** [comment] 2021-01-12 10:22
Acquiring a lock in a separate transaction is only necessary if it is not allowed that the job will be 'retried' by another server if the transaction is rolled back.
The lock mechanism is tested for exclusivity even over separate open transactions: Once the INSERT statement is executed within a transaction, the lock is obtained, even before the transactions is committed. Other threads trying to obtain the same lock will wait until the transaction finishes (or they timeout themselves) to obtain the lock or to find out that they did not obtain it.
PR #1387 will provide an attribute transactionAttribute for Locker, on top of the same attribute for Job. The one for Locker can be set to 'RequiresNew' to execute the Locker in its own transaction.
It is probably also important to set the type of the Locker to 'P', to avoid the lock being released after the job has finished.

**Closed** 2021-01-15 13:52 UTC

**Comment by gvanbrakel** [comment] 2021-01-20 12:17
Ricardo schreef op 20-1-2021:
Ik heb het lokaal opnieuw getest met Oracle en kan het probleem niet meer reproduceren. Ik vermoed met de beschrijving die je gegeven hebt voor Jeroen, dat ik daar in mijn geval ook tegenaan ben gelopen en dat ik op het verkeerde been ben gezet omdat ik de lock niet terug zag komen in de database omdat insert en delete samen gecommit werden doordat ik het transactionAttribute op Required had gezet.
