### ISSUE TITLE
Permissions to enable Ladybug debugger have changed

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#768] opened 2020-05-28 13:26 UTC
**Describe the bug**
Enable Ladybug Debugger checkbox has been added to the Environment Variables page and now also needs to be enabled to enable debugging by the Ladybug apart from changing Report generator in the Ladybug Options. To change Report generator enabled it is sufficient to have IbisDataAdmin rights. For the new checkbox you need IbisAdmin rights. This means people with IbisDataAdmin permission who could enable the Ladybug in de past are not able to do so anymore.

**Reporter**
Jaco de Groot

**Category**
 - Ladybug (debugging tool)

**To Reproduce**
1. Go to Environment Variables page
2. Change Enable Ladybug Debugger
3. Click Send button
4. Load page again and checkbox has been changed to previous state (unless you have IbisAdmin permission)

**Expected behavior**
Have the same permissions being applied to Enable Ladybug Debugger as to Report generator enabled. And keep it working for IbisDataAdmin or otherwise explain this new behavior to the user and make it clear what needs to be done to enable the Ladybug debugger again.

**Screenshots**
-

**Environment:**
 - WebSphere A and P
 - Crome and Firefox
 - IAF Version 7.5 RC2

**Additional context**
-

**Comment by nielsm5** [comment] 2020-05-29 14:57
This should be fixed in the RC3, duplicate of #660

**Comment by nielsm5** [comment] 2020-11-16 13:23
IAF console rol op `IbisDataAdmin` zetten

**Closed** 2020-11-26 10:59 UTC
Labels: Frank Console
