### ISSUE TITLE
Ibis4Publishing : Unable to upload jar file : FF version  7.5-RC3

### ISSUE THREAD

**Issue by Moulib1978** [ibissource/iaf#1810] opened 2021-05-14 12:30 UTC
In ibis4Publishing, when we are going to upload a jar file it is saying "Successfully uploaded configuration" but actually upload is not done.
On the migrated server we are getting the error: 
Failed to upload Configuration: (DuplicateKeyException): (SQLIntegrityConstraintViolationException) SQLState [23000], errorCode [1]: (OracleDatabaseException) ORA-00001: Schending van UNIQUE-beperking (IBIS4PUBLISONLINE_MGR.PK_IBISCONFIG).

when uploading with 'multiple configuration' checked, it's showing an error:
Failed to upload Configuration: (SQLIntegrityConstraintViolationException) SQLState [23000], errorCode [1400]: (OracleDatabaseException) ORA-01400: Kan geen NULL invoegen in ("IBIS4PUBLISONLINE_MGR"."IBISCONFIG"."VERSION").

**Comment by nielsm5** [comment] 2021-05-16 15:19
It seems you're trying to add multiple configurations at once. One of which causes this issue by not having a valid/proper config version.

**Comment by nielsm5** [comment] 2021-05-20 12:13
Seems to be a duplicate of https://github.com/ibissource/iaf/issues/1337, the fix would be to upgrade to the latest stable release (`7.5.1`).

**Closed** 2021-05-20 12:17 UTC
