### ISSUE TITLE
Ibisdoc application does not work anymore

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#750] opened 2020-05-25 08:45 UTC
**Describe the bug**
The ibisdoc application does not work anymore. The webpage does not show any data, see picture:

![image](https://user-images.githubusercontent.com/6784732/82795295-12618f80-9e74-11ea-9574-912179ae6023.png)

**Category**
 - Frank Framework

**To Reproduce**
1. Start the Frank!Runner or go to ibis4example.ibissource.org
2. Go to Webservices
3. Click "The new ibisdoc application"
4. The page shown above appears, without data.

**Expected behavior**
The list to the top shows subjects like "pipe", "sender", "listener", etc. Depending on the chosen subject, the bottom list shows all the pipes, all the senders, or...

**Screenshots**
Already shown

**Environment:**
 - Frank!Framework version 7.6-20200525.101351
 - Microsoft Edge
 - The bug both happens on ibis4example.ibissource.org and with the Frank!Runner

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment] 2020-05-25 09:48
Duplicate of #744

**Closed** 2020-05-25 19:47 UTC

**Comment by mhdirkse** [comment] 2020-05-26 08:09
Verified.
