### ISSUE TITLE
Ladybug report messed up when parallel processing

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3875] opened 2022-10-18 09:56 UTC
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When having an iterating pipe with parallel=true and multiple threads, the Ladybug report might end up a mess with non-related threads opening and closing inside each other.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7.2
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment] 2023-01-03 13:40
Tried to reproduce it with Frank2Example3 with F!F 7.7.2 adding parallel="true" to the ForEachChildElementPipe in HelloLines and removing all other pipes and adding a 1000 ms delay to the HelloWorld adapter but could not reproduce it (also tried with an input xml having 100 lines to start 100 threads.

Maybe this issue is fixed with https://github.com/ibissource/iaf/issues/4224

**Closed by jacodg** 2023-01-03 13:40 UTC
