### ISSUE TITLE
Browse Tables java.lang.stackoverflowerror

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#450] opened 2020-02-25 13:53 UTC
**Describe the bug**
The browse database tables option gives a technical error

**Category**
 - Frank Console

**To Reproduce**
1. Go to JDBC
2. Click on Browse Tables
3. Select realm JDBC
4. TableName ibisconfig 
5. SEND button
6. see error on top of page

**Expected behavior**
showing the database table of ibisconfig

**Screenshots**
![error browse tables Frank Console PNG](https://user-images.githubusercontent.com/3921911/75253277-7c6b8980-57de-11ea-9d81-da06d661f49d.PNG)

**Environment:**
- Browse  chrome
 - IAF Version 7.5.xxxxxx

**Additional context**

**Comment by nielsm5** [comment] 2020-03-03 10:17
Unable to reproduce, was already fixed in #371
Further improved logging when an error occurs

**Closed** 2020-03-11 13:57 UTC
Labels: bug
