### ISSUE TITLE
When you open the Frank!Console in Microsoft Edge, you cannot see logfiles

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#628] opened 2020-04-22 15:31 UTC
**Describe the bug**
When you open the Frank!Console in Microsoft Edge, you cannot see logfiles. In Google Chrome you can.

**Category**
 - Frank Console

**To Reproduce**
1. Start the Frank!Runner again. To produce this error, the Frank!Runner was executed earlier resulting in some log files.
2. Open Microsoft Edge and browse to http://localhost.
3. In the main menu, click "Logging".
4. Click some logfile.
5. An animation is shown that the logfile is being loaded. That animation does not go away, also not when you refresh your browser. The logfile does not appear.

**Expected behavior**
The chosen logfile should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/6784732/80001637-e0e55500-84be-11ea-9b61-0e11a08c82c1.png)

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - Frank!Framework version 7.6-20200422.121508

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment] 2020-04-24 18:15
I think this is a duplicate of #629 where certain callbacks are not being 'called'.

**Closed** 2020-04-28 06:41 UTC

**Comment by mhdirkse** [comment] 2020-04-28 07:35
I verified that the issue has been fixed. Thanks.
