### ISSUE TITLE
Unable to get rid of configuration warnings related to message/error store

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1725] opened 2021-04-20 08:15 UTC
**Describe the issue**
I have a receiver with transaction=required and a messagestore listener.

Whenever I do have an external error storage configured, the framework does not allow my adapter to start:
![image](https://user-images.githubusercontent.com/37303445/115361230-ab9e4080-a1c0-11eb-8ed5-3ff87d5cf3e0.png)

So I remove the message log...:
![image](https://user-images.githubusercontent.com/37303445/115361919-56166380-a1c1-11eb-9cb9-600036d958fc.png)

So I remove the error log..:
![image](https://user-images.githubusercontent.com/37303445/115360243-be644580-a1bf-11eb-8549-b9a0b82d7c1f.png)

This is kinda odd to me, what am I supposed to do? My adapter only starts without the error/message logs...

Please warn about the message AND error log at ONCE instead of having to remove one the two, restart, find out the other also has to be removed, restart again...

**Reporter**
Laurens

**To Reproduce**
receiver with transaction=required and a messagestore listener.

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL] H2
 - Browser: [e.g. Chrome, Safari, Edge, Firefox] Chrome

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment] 2021-05-14 13:28
Laurens, I looked into this issue today, and could not reproduce it. It might have been fixed in the mean time.
Could you retest and confirm if it still exists or not?
If it still is a problem, please update the description box under 'Environment', following the instructions presented there.

**Closed** 2021-05-17 08:25 UTC
