### ISSUE TITLE
Server Error charset

### ISSUE THREAD

**Issue by francisgw** [ibissource/iaf#825] opened 2020-06-16 11:08 UTC
**Describe the bug**
From IAF 7.6-20200615.172252 onwards, when testing an adapter the browser gives a server error warning

**Category**
 - Frank Console

**To Reproduce**
1. Clone new frank-runner
2. Install frank-runner
3. Go to testing and test example adapter

**Screenshots**
![52466c2f-670c-429a-8a24-1cda18745f87](https://user-images.githubusercontent.com/67001993/84767213-5575d500-afd2-11ea-8887-db5d48e263ae.jpg)

**Environment:**
 - Apache-tomcat-7.0.100
 - Edge, Brave
 - IAF Version 7.6-20200615.172252

**Comment by Laurens-makel** [comment] 2020-06-16 11:11
Duplicate of #820

**Closed** 2020-06-16 11:23 UTC
