### ISSUE TITLE
Logging info to MDC when message is moved to the errorstore

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#4614] opened 2023-03-09 08:58 UTC
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
It would be nice to be able to monitor when a message is put in the error store (including some functional information)
We forward the MDC message.json to splunk where we can trace the message based on functional keys 

**Reporter**
jjansenvr

**Comment by jacodg** [comment] 2023-03-13 12:49
Exclude functional information for first iteration

**Comment by nielsm5** [comment] 2023-06-26 12:21
Duplicate of #4753 ?

**Closed by nielsm5** 2023-06-26 12:21 UTC
