### ISSUE TITLE
Unexpected null sessionkey when sub-adapter input message is also stored in session 

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#5356] opened 2023-09-08 15:38 UTC
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Related to #5287. A SoapWrapperPipe unwraps the input SOAP-message and stores it in a sessionkey "UnwrapMessageResult". Later when wrapping the response message with another SoapWrapperPipe, the sessionkey is null.

The difference since the recent fix for this issue, is that now it always happens, not only with messages > 500kb. The Adapter is not overwriting the sessionkey like it did before and there is only 1 unwrap being done. Additionally the SoapWrapperPipe is now throwing the exception: `nl.nn.adapterframework.core.PipeRunException: Pipe [WrapGenereerZaakIdentificatie_Du02Response] Unexpected exception during (un)wrapping : (XPathException) Template xsl:initial-template does not exist`. 

The issue seems to be only happening around SoapWrapperPipes. Compared to our refactor of this adapter, where the issue does not exist, the only difference I can see is that the sessionkey is not stored by the SoapWrapperPipe, but by a PutInSessionPipe. Also with the refactored version, the result of the SoapWrapperPipe is only entering the LocalIbisSender, but it is not saved as a sessionkey and then later used.

**Reporter**
M. Lenterman

**To Reproduce**

**Screenshots**

**Configuration**
[Pipeline SoapEndpointRouter_VrijeBerichten - Unexpected null sessionkey SoapWrapperPipe.zip](https://github.com/ibissource/iaf/files/12561417/Pipeline.SoapEndpointRouter_VrijeBerichten.-.Unexpected.null.sessionkey.SoapWrapperPipe.zip)

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9-20230907.223421: ZaakBrug
Running on 2c09a46ee98c using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (1.8.0_372-b07)
Heap size: 986M, total JVM memory: 2254M
Free disk space: 211GB, total disk space: 251GB
Up since: 2023-09-08 17:03:50 (32m) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by tnleeuw** [comment] 2023-09-11 08:12
The issue is caused by the fact that the message stored in the session key was also used as input to sub-adapter. After the sub-adapter was completed, this message was closed. The side effect of that was closing the session key.

The fix is not to close any message in the sub-adapter that are also used in the session of the calling adapter.

**Closed** 2023-09-13 08:26 UTC
Labels: Bug
