### ISSUE TITLE
"Export all / export selected"-functionality is missing in GUI 3.0

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#2941] opened 2022-03-29 10:07 UTC
"The export all/export selected"-functionality is missing in GUI 3.0. This is functionality is very important and used a lot (after applying some filters) by some teams. Can you please add this functionality to GUI 3.0 in the 7.7 stable release?
(Or keep the old GUI available in the 7.7, that's fine as well)

![export all](https://user-images.githubusercontent.com/30295058/160587964-af0aeca1-27a4-47b0-920d-a107bf329d5e.PNG)

**Comment by nielsm5** [comment] 2022-03-29 11:22
This seems to be a duplicate of #2825.

**Comment by laura-dimitra** [comment] 2022-03-29 14:00
Yes, it is. Sorry, I'm always checking the open issues reporting an issue, but sometimes it's hard to find the right keywords between the open tickets.

**Closed** 2022-03-30 09:12 UTC
