### ISSUE TITLE
url param containing %2F get unescaped in httpsender

### ISSUE THREAD

**Issue by VBPham** [ibissource/iaf#571] opened 2020-04-02 12:34 UTC
**Describe the bug**
In my case i have a pipe that gets an signed s3 url which contains "%2F" which I save in a sessionkey and use later as a urlparam for the httpsender. The urlparam gets resolved properly with the "%2F" in tact but the actual executing of the method occurs on the unescaped url i.e. "%2F" gets unescaped to "/" 

**Category**
 - Frank Framework

**To Reproduce**

**Expected behavior**
executing of the method is on the url as is and not change it on the last step, which is also not visible in the ladybug

**Screenshots**

**Environment:**

**Additional context**

**Comment by VBPham** [comment] 2020-04-07 09:10
% gets escaped to %25 in httpclient presumably

**Comment by nielsm5** [comment] 2020-05-26 12:48
I'm going to close this as it's not reproducible. I've done some extensive integration tests and all looks fine. 
Your tests might have failed over differently encode html escaped characters such as `+` vs `%20`. Since both are correct there is not much we can do at this point.

Please reopen this issue if you are still experiencing issues!

**Closed by nielsm5** 2020-05-26 12:48 UTC
Labels: bug
